class Socket_Services_List:
    NONE = "NONE"
    SERVER = "server"
    SENSORS = "sensor_client"
    KEYBOARD = "keyboard_client"
    USERINTERFACE = "ui_client"
    REMOTE = "remotr_client"
    SAMPLE = "sample_client"
    WEBCAM = "webcam_client" 
    SPEAKER = "speaker_client"
    ACTUATORS = "actuators_client"
    TELEGRAM = "telegram_client"
    ARDUINO_READ_WRITE = "arduino_read_wrote_test_client"
    LIDAR = "lidar_client"
    CONSOLE = "console_client"
    JOYSTICK = "joystick_client"