RunnableClients = [('SERVER','Socket_Server.py', 1),
             ('keyboard','Socket_Client_Keyboard.py', 1),
            ('sensors','Socket_Client_Sensors.py',0),
            ('lidar','Socket_Client_Lidar.py',  0),
            ('actuators','Socket_Client_Actuators.py', 0),
            ('speaker','Socket_Client_Speaker.py', 0),
            ('telegram','Socket_Client_Telegram.py',0),
            ('ui','Socket_Client_UI.py', 0),
            ('webcam','Socket_Client_WebCam.py', 0),
            ('remote','Socket_Client_Remote.py',0),
            ('sample',"Socket_Client_Sample.py",1),
            ('console',"Socket_Client_Console.py", 1),    
            ('joy',"Socket_Client_Joystick.py", 0),
            ]
