class Socket_Services_List:
    NONE = "NONE"
    SERVER = "SERVER"
    SENSORS = "SENSORS_Client"
    KEYBOARD = "KEYBOARD_Client"
    USERINTERFACE = "UI_Client"
    REMOTE = "REMOTE_Client"
    SAMPLE = "SAMPLE_Client"
    WEBCAM = "WEBCAM_Client" 
    SPEAKER = "SPEAKER_Client"
    ACTUATORS = "ACTUATORS_Client"
    TELEGRAM = "TELEGRAM_Client"
    ARDUINO_READ_WRITE = "ARDUINO_READ_WRITE_TEST_Client"
    LIDAR = "LIDAR_Client"
    CONSOLE = "CONSOLE_Client"
    JOYSTICK = "JOYSTICK_Client"